version: "3.3"
services:
  sftp.nav.no:
    image: atmoz/sftp
    volumes:
      - ./testresources/outbound:/home/srvSykepengevedtakSPK/outbound
      - ./testresources/inbound:/home/srvSykepengevedtakSPK/inbound
      - ./testresources/outbound:/home/srvSykepengevedtakKLP/outbound
      - ./testresources/inbound:/home/srvSykepengevedtakKLP/inbound
      - ./testresources/.ssh/id_ed25519.pub:/home/srvSykepengevedtakSPK/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/id_ed25519.pub:/home/srvSykepengevedtakKLP/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
    ports:
      - "2222:22"
    command: srvSykepengevedtakSPK::1001 srvSykepengevedtakKLP::1002
  spokelse.tbd.svc.nais.local:
    build: mockserver
    environment:
      FLASK_RUN_PORT: "80"
      FLASK_RUN_HOST: "0.0.0.0"
  spissnok:
    build: .
    environment:
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://sporbar.tbd.svc.nais.local/token
      AZURE_APP_CLIENT_ID: wowclientid
      AZURE_APP_CLIENT_SECRET: wowsecret
      SPORBAR_CLIENT_ID: wowscopeclientid
      SFTP_HOST: sftp.nav.no
    volumes:
      - ./testresources/.ssh/id_ed25519:/var/run/ssh-keys/id_ed25519:ro
      - ./testresources/known_hosts:/var/run/ssh-keys/known_hosts:ro