version: "3.3"
services:
  sftp.nav.no:
    image: atmoz/sftp
    volumes:
      - ./testresources/outbound:/home/denvercoder9/outbound
      - ./testresources/inbound:/home/denvercoder9/inbound
      - ./testresources/.ssh/id_ed25519.pub:/home/denvercoder9/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
    ports:
      - "2222:22"
    command: denvercoder9::1001 denvercoder10::1002
  spissnok:
    build: .
    volumes:
      - ./testresources/.ssh/id_ed25519:/id_ed25519:ro
      - ./testresources/known_hosts:/known_hosts:ro