version: "3.3"
services:
  sftp.nav.no:
    image: atmoz/sftp
    volumes:
      - ./testresources/outbound:/home/srvSykepengevedtakSPK/outbound
      - ./testresources/inbound:/home/srvSykepengevedtakSPK/inbound
      - ./testresources/outbound:/home/srvSykepengevedtakKLP/outbound
      - ./testresources/inbound:/home/srvSykepengevedtakKLP/inbound
      - ./testresources/outbound:/home/srvSykepengevedtakAFP/outbound
      - ./testresources/inbound:/home/srvSykepengevedtakAFP/inbound
      - ./testresources/.ssh/id_ed25519.pub:/home/srvSykepengevedtakSPK/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/id_ed25519.pub:/home/srvSykepengevedtakKLP/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/id_ed25519.pub:/home/srvSykepengevedtakAFP/.ssh/keys/id_ed25519.pub:ro
      - ./testresources/.ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
    command: srvSykepengevedtakKLP::1001 srvSykepengevedtakSPK::1002 srvSykepengevedtakAFP::1003
  spokelse.tbd.svc.nais.local:
    build: mockserver
    environment:
      FLASK_RUN_PORT: "80"
      FLASK_RUN_HOST: "0.0.0.0"
  spissnok:
    build: .
    environment:
      AZURE_OPENID_CONFIG_TOKEN_ENDPOINT: http://spokelse.tbd.svc.nais.local/token
      AZURE_APP_CLIENT_ID: wowclientid
      AZURE_APP_CLIENT_SECRET: wowsecret
      SPORBAR_CLIENT_ID: wowscopeclientid
      SFTP_HOST: sftp.nav.no
      SPOKELSE_URL: http://spokelse.tbd.svc.nais.local
      KJOR_SOM_JOBB: "true"
    volumes:
      - ./testresources/.ssh/id_ed25519:/var/run/ssh-keys/id_ed25519:ro
      - ./testresources/known_hosts:/var/run/ssh-keys/known_hosts:ro
      - ./testresources/logs:/secure-logs
    depends_on:
      - spokelse.tbd.svc.nais.local
      - sftp.nav.no