apiVersion: nais.io/v1alpha1
kind: Naisjob
metadata:
  name: spissnok
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: SPORBAR_CLIENT_ID
      value: api://dev-fss.tbd.sporbar/.default
