apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: spissnok
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  schedule: "*/5 * * * *"
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  filesFrom:
    - secret: spissnok-ssh-keys
      mountPath: /var/run/ssh-keys
  accessPolicy:
    outbound:
      rules:
        - application: prometheus
          namespace: nais
  env:
    - name: SPORBAR_CLIENT_ID
      value: api://dev-gcp.tbd.spokelse/.default
    - name: SPOKELSE_URL
      value: https://spokelse.intern.dev.nav.no
    - name: SFTP_HOST
      value: sftp-q.nav.no
    - name: PUSH_GATEWAY_ADDRESS
      value: http://prometheus-pushgateway.nais-system.svc.nais.local:9091
