apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: spissnok
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  schedule: "00 14 * * */1"
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  filesFrom:
    - secret: spissnok-ssh-keys
      mountPath: /var/run/ssh-keys
  accessPolicy:
    outbound:
      external:
        - host: sftp.nav.no
          ports:
            - name: SFTP
              port: 22
              protocol: TCP
  env:
    - name: SPORBAR_CLIENT_ID
      value: api://prod-gcp.tbd.spokelse/.default
    - name: SPOKELSE_URL
      value: http://spokelse
    - name: SFTP_HOST
      value: sftp.nav.no
