apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spissnok
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 50m
      memory: 64Mi
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  replicas:
    min: 1
    max: 1
  webproxy: true
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  filesFrom:
    - secret: spissnok-ssh-keys
      mountPath: /var/run/ssh-keys
  accessPolicy:
    outbound:
      rules:
        - application: spokelse
      external:
        - host: sftp.nav.no
          ports:
            - port: 22
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spissnok-v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: SPORBAR_CLIENT_ID
      value: api://prod-gcp.tbd.spokelse/.default
    - name: SPOKELSE_URL
      value: http://spokelse
    - name: SFTP_HOST
      value: sftp.nav.no
